[package]
name = "wgame-examples"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["wgame/default"]
web = ["wgame/web"]

[dependencies]
wgame.workspace = true
wgame-utils.workspace = true
futures.workspace = true
glam.workspace = true
rgb.workspace = true
